### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by aghabri** [aghabri/test#1]
[](url)
[CRA_Aziz_GHABRI_SEPTEMBRE_2022.pdf](https://github.com/aghabri/test/files/9850580/CRA_Aziz_GHABRI_SEPTEMBRE_2022.pdf)

**Comment by aghabri** [comment]
[Avis_d_impot_2022_sur_les_revenus_2021.pdf](https://github.com/aghabri/test/files/9850611/Avis_d_impot_2022_sur_les_revenus_2021.pdf)

**Comment by aghabri** [comment]
[01_Liste pièces_Décret_janvier 2021.pdf](https://github.com/aghabri/test/files/9850636/01_Liste.pieces_Decret_janvier.2021.pdf)

**Comment by aghabri** [comment]
![IMG](https://user-images.githubusercontent.com/25765260/197500034-0eb18a36-7145-4d10-8209-007c91108df1.jpg)

**Comment by aghabri** [comment]
[Bulletin de Decembre 20.pdf](https://github.com/aghabri/test/files/9876684/Bulletin.de.Decembre.20.pdf)
[Bulletin de Novembre 20.pdf](https://github.com/aghabri/test/files/9876685/Bulletin.de.Novembre.20.pdf)
[Avis_d_impot_2022_sur_les_revenus_2021.pdf](https://github.com/aghabri/test/files/9876686/Avis_d_impot_2022_sur_les_revenus_2021.pdf)

**Comment by aghabri** [comment]
[Avis_d_impot_2021_sur_les_revenus_2020.pdf](https://github.com/aghabri/test/files/9876718/Avis_d_impot_2021_sur_les_revenus_2020.pdf)
[Avis_d_impot_2020_sur_les_revenus_2019.pdf](https://github.com/aghabri/test/files/9876719/Avis_d_impot_2020
[Avis_d_impot_2019_sur_les_revenus_2018.pdf](https://github.com/aghabri/test/files/9876721/Avis_d_impot_2019_sur_les_revenus_2018.pdf)
_sur_les_revenus_2019.pdf)

**Comment by aghabri** [comment]
[Avis_d_impot_2020_sur_les_revenus_2019.pdf](https://github.com/aghabri/test/files/9876740/Avis_d_impot_2020_sur_les_revenus_2019.pdf)

**Comment by aghabri** [comment]
[GHABRI_AZIZ_11_2020.pdf](https://github.com/aghabri/test/files/9878204/GHABRI_AZIZ_11_2020.pdf)
[GHABRI_AZIZ_12_2020.pdf](https://github.com/aghabri/test/files/9878207/GHABRI_AZIZ_12_2020.pdf)
[GHABRI_AZIZ_12_2019.pdf](https://github.com/aghabri/test/files/9878209/GHABRI_AZIZ_12_2019.pdf)
[GHABRI_AZIZ_11_2019.pdf](https://github.com/aghabri/test/files/9878212/GHABRI_AZIZ_11_2019.pdf)

**Comment by aghabri** [comment]
[CRA_Aziz_GHABRI_OCTOBRE_2022.pdf](https://github.com/aghabri/test/files/9879564/CRA_Aziz_GHABRI_OCTOBRE_2022.pdf)

**Comment by aghabri** [comment]
https://www.devenez.fr/espace-candidats/les-offres-en-cours/consultant-testing-agile/

**Comment by aghabri** [comment]
[Olfa_GHABRI_CV.pdf](https://github.com/aghabri/test/files/10005102/Olfa_GHABRI_CV.pdf)

**Comment by aghabri** [comment]
[AttestationHebergement.pdf](https://github.com/aghabri/test/files/10013435/AttestationHebergement.pdf)

**Comment by aghabri** [comment]
[fiche_elior_GHABRI.pdf](https://github.com/aghabri/test/files/10014172/fiche_elior_GHABRI.pdf)

**Comment by aghabri** [comment]
[Catalogue umdp NOEL 2022 v3.pdf](https://github.com/aghabri/test/files/10084948/Catalogue.umdp.NOEL.2022.v3.pdf)

**Comment by aghabri** [comment]
[CRA_Aziz_GHABRI_11_2022.pdf](https://github.com/aghabri/test/files/10122118/CRA_Aziz_GHABRI_11_2022.pdf)

**Comment by aghabri** [comment]
[invoice (1).pdf](https://github.com/aghabri/test/files/10209515/invoice.1.pdf)
[invoice (2).pdf](https://github.com/aghabri/test/files/10209516/invoice.2.pdf)
[invoice.pdf](https://github.com/aghabri/test/files/10209518/invoice.pdf)

**Comment by aghabri** [comment]
[CRA_Aziz_GHABRI_1222.pdf](https://github.com/aghabri/test/files/10295574/CRA_Aziz_GHABRI_1222.pdf)

**Comment by aghabri** [comment]
[CRA_Aziz_GHABRI_0123.pdf](https://github.com/aghabri/test/files/10567509/CRA_Aziz_GHABRI_0123.pdf)

**Comment by aghabri** [comment]
[CRA_Aziz_GHABRI_022023.pdf](https://github.com/aghabri/test/files/10822529/CRA_Aziz_GHABRI_022023.pdf)

**Comment by aghabri** [comment]
[Nsira sami (4) (2).pdf](https://github.com/aghabri/test/files/10979773/Nsira.sami.4.2.pdf)
[Java-Interview-example-main.zip](https://github.com/aghabri/test/files/10979775/Java-Interview-example-main.zip)
[JeeQuestionsInterview-main.zip](https://github.com/aghabri/test/files/10979776/JeeQuestionsInterview-main.zip)
[Question Spring Boot.docx](https://github.com/aghabri/test/files/10979777/Question.Spring.Boot.docx)
[Angular-Interview-example-main.zip](https://github.com/aghabri/test/files/10979778/Angular-Interview-example-main.zip)

**Comment by aghabri** [comment]
[FullStack Developer_Ameur Taboui-3.pdf](https://github.com/aghabri/test/files/11029496/FullStack.Developer_Ameur.Taboui-3.pdf)

**Comment by aghabri** [comment]
[05_-_SOA_-_JAX-WS.pdf](https://github.com/aghabri/test/files/11040923/05_-_SOA_-_JAX-WS.pdf)

**Comment by aghabri** [comment]
[05_-_SOA_-_JAX-WS.pptx](https://github.com/aghabri/test/files/11040981/05_-_SOA_-_JAX-WS.pptx)

**Comment by aghabri** [comment]
[CRA_Aziz_GHABRI_032023.pdf](https://github.com/aghabri/test/files/11049328/CRA_Aziz_GHABRI_032023.pdf)

**Comment by aghabri** [comment]
[GHABRI_CP_28386.pdf](https://github.com/aghabri/test/files/11145983/GHABRI_CP_28386.pdf)

**Comment by aghabri** [comment]
[data.zip](https://github.com/aghabri/test/files/11146041/data.zip)

**Comment by aghabri** [comment]
https://github.com/provectus/kafka-ui/releases/download/v0.5.0/kafka-ui-api-v0.5.0.jar

**Comment by aghabri** [comment]
[VALIDATION_VLS-TS_9924093578_20230201_FR (1).pdf](https://github.com/aghabri/test/files/11484539/VALIDATION_VLS-TS_9924093578_20230201_FR.1.pdf)

**Comment by aghabri** [comment]
[doc03331920230524175735.pdf](https://github.com/aghabri/test/files/11562456/doc03331920230524175735.pdf)

**Comment by aghabri** [comment]
[25052023_Scan_122829.pdf](https://github.com/aghabri/test/files/11563811/25052023_Scan_122829.pdf)

**Comment by aghabri** [comment]
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.jaxrs.config.BeanConfig;
import io.swagger.jaxrs.listing.SwaggerSerializers;

import javax.servlet.ServletConfig;
import javax.ws.rs.*;
import javax.ws.rs.core.Application;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import java.util.HashSet;
import java.util.Set;

@Api(value = "/example", description = "Exemple de service REST")
@Path("/example")
public class ExampleWebService extends Application {

    @Context
    private ServletConfig servletConfig;

    public ExampleWebService() {
        initSwagger();
    }

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> classes = new HashSet<>();
        classes.add(SwaggerSerializers.class);
        return classes;
    }

    private void initSwagger() {
        BeanConfig beanConfig = new BeanConfig();
        beanConfig.setVersion("1.0.0");
        beanConfig.setSchemes(new String[]{"http"});
        beanConfig.setHost("localhost:8080");
        beanConfig.setBasePath("/example");
        beanConfig.setResourcePackage("com.example");
        beanConfig.setPrettyPrint(true);
        beanConfig.setScan(true);
    }

    @GET
    @ApiOperation(value = "Obtenir un exemple", notes = "Récupère un exemple")
    @Produces(MediaType.APPLICATION_JSON)
    public Example getExample() {
        Example example = new Example();
        example.setId(1);
        example.setName("Exemple");
        return example;
    }

    @POST
    @ApiOperation(value = "Créer un exemple", notes = "Crée un nouvel exemple")
    @Consumes(MediaType.APPLICATION_JSON)
    public void createExample(@ApiParam(value = "Exemple à créer", required = true) Example example) {
        // Logique de création de l'exemple
    }
}

class Example {
    private int id;
    private String name;

    // Getters et setters
}

**Comment by aghabri** [comment]
[swagger-jaxrs-1.5.0.jar.txt](https://github.com/aghabri/test/files/11679728/swagger-jaxrs-1.5.0.jar.txt)

**Comment by aghabri** [comment]
<servlet>
    <servlet-name>Jersey REST Service</servlet-name>
    <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
    <init-param>
        <param-name>jersey.config.server.provider.packages</param-name>
        <param-value>com.example</param-value>
    </init-param>
    <load-on-startup>1</load-on-startup>
</servlet>

<servlet-mapping>
    <servlet-name>Jersey REST Service</servlet-name>
    <url-pattern>/api/*</url-pattern>
</servlet-mapping>

**Comment by aghabri** [comment]
<servlet>
    <servlet-name>Jersey REST Service</servlet-name>
    <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
    <init-param>
        <param-name>jersey.config.server.provider.packages</param-name>
        <param-value>com.example</param-value>
    </init-param>
    <load-on-startup>1</load-on-startup>
</servlet>

<servlet-mapping>
    <servlet-name>Jersey REST Service</servlet-name>
    <url-pattern>/api/*</url-pattern>
</servlet-mapping>

**Comment by aghabri** [comment]
[new 13.txt](https://github.com/aghabri/test/files/11692572/new.13.txt)

**Comment by aghabri** [comment]
[myapp.txt](https://github.com/aghabri/test/files/11692735/myapp.txt)

**Comment by aghabri** [comment]
[web.txt](https://github.com/aghabri/test/files/11692904/web.txt)

**Comment by aghabri** [comment]
weblogic.application.ModuleException: [HTTP:101216]Servlet: "Jersey Servlet" failed to preload on startup in Web application: "gdsWebServiceRest.war".
java.lang.NoClassDefFoundError: org.objectweb.asm.ClassVisitor
	at java.lang.J9VMInternals.verifyImpl(Native Method)

**Comment by aghabri** [comment]
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/api")
public class MyWebService {

  @GET
  @Path("/hello")
  @Produces(MediaType.TEXT_PLAIN)
  public String sayHello() {
    return "Hello, world!";
  }
}

**Comment by aghabri** [comment]
<web-app>
  <servlet>
    <servlet-name>JerseyServlet</servlet-name>
    <servlet-class>org.glassfish.jersey.servlet.ServletContainer</servlet-class>
    <init-param>
      <param-name>javax.ws.rs.Application</param-name>
      <param-value>com.example.MyApplication</param-value>
    </init-param>
    <load-on-startup>1</load-on-startup>
  </servlet>
  
  <servlet-mapping>
    <servlet-name>JerseyServlet</servlet-name>
    <url-pattern>/rest/*</url-pattern>
  </servlet-mapping>
</web-app>

**Comment by aghabri** [comment]
[web.txt](https://github.com/aghabri/test/files/11749252/web.txt)

**Comment by aghabri** [comment]
import javax.ws.rs.core.Application;
import java.util.HashSet;
import java.util.Set;

public class MyApplication extends Application {
  
  @Override
  public Set<Class<?>> getClasses() {
    Set<Class<?>> classes = new HashSet<>();
    classes.add(MyWebService.class);
    return classes;
  }
}

**Comment by aghabri** [comment]
[myapp (2).txt](https://github.com/aghabri/test/files/11749266/myapp.2.txt)

**Comment by aghabri** [comment]
[myaappppp.txt](https://github.com/aghabri/test/files/11749268/myaappppp.txt)

**Comment by aghabri** [comment]
[jersey-bundle-1.1.5.jar.txt](https://github.com/aghabri/test/files/11749414/jersey-bundle-1.1.5.jar.txt)
[jersey-server-1.1.5.jar.txt](https://github.com/aghabri/test/files/11749415/jersey-server-1.1.5.jar.txt)
[jersey-core-1.1.5.jar.txt](https://github.com/aghabri/test/files/11749416/jersey-core-1.1.5.jar.txt)

**Comment by aghabri** [comment]
[myaappppp.txt](https://github.com/aghabri/test/files/11749434/myaappppp.txt)
[web.txt](https://github.com/aghabri/test/files/11749435/web.txt)

**Comment by aghabri** [comment]
weblogic.application.ModuleException: [HTTP:101216]Servlet: "JerseyServlet" failed to preload on startup in Web application: "gdsWebServiceRest.war".
java.lang.NoClassDefFoundError: org.objectweb.asm.ClassVisitor
	at java.lang.J9VMInternals.verifyImpl(Native Method)

**Comment by aghabri** [comment]
[asm-3.1.jar.txt](https://github.com/aghabri/test/files/11749601/asm-3.1.jar.txt)

**Comment by aghabri** [comment]
com.sun.jersey.core.spi.scanning.ScannerException: IO error when scanning jar zip:/applis/gdsd/weblogic/domaineGDS/servers/gdsdServer01/tmp/_WL_user/gdsWebServiceRest/enie1w/war/WEB-INF/lib/_wl_cls_gen.jar!/com/socgen/gds/synoe
	at com.sun.jersey.core.spi.scanning.uri.JarZipSchemeScanner.scan(JarZipSchemeScanner.java:75)

**Comment by aghabri** [comment]
Icône de message - Erreur Impossible d'accéder à l'application sélectionnée.
Icône de message - Erreur Exception in AppMerge flows' progression
Icône de message - Erreur Exception in AppMerge flows' progression
Icône de message - Erreur VALIDATION PROBLEMS WERE FOUND problem: cvc-enumeration-valid: string value '3.0' is not a valid enumeration value for web-app-versionType in namespace http://java.sun.com/xml/ns/javaee:<null>

**Comment by aghabri** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://java.sun.com/xml/ns/javaee"
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
	id="WebApp_ID" version="3.0">

	<display-name>gdsWebServiceRest</display-name>
	<listener>
		<listener-class>
			org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap</listener-class>
	</listener>
	<servlet>
		<servlet-name>Resteasy</servlet-name>
		<servlet-class>
			org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher</servlet-class>
		<init-param>
			<param-name>javax.ws.rs.Application</param-name>
			<param-value>com.socgen.ws.server.ApplicationInitializer</param-value>
		</init-param>
	</servlet>
	<servlet-mapping>
		<servlet-name>Resteasy</servlet-name>
		<url-pattern>/*</url-pattern>
	</servlet-mapping>

</web-app>

**Comment by aghabri** [comment]
Caused By: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=org/jboss/resteasy/plugins/server/servlet/ResteasyBootstrap, offset=6
	at java.lang.ClassLoader.defineClassImpl(Native Method)

**Comment by aghabri** [comment]
L'erreur `java.lang.UnsupportedClassVersionError` se produit lorsqu'une classe a été compilée avec une version plus récente de Java que celle utilisée lors de l'exécution. Dans votre cas, l'erreur indique que la classe `org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap` a été compilée avec une version de Java supérieure à celle utilisée par votre environnement d'exécution.

Il est possible que la version de Resteasy que vous utilisez soit incompatible avec la version de Java utilisée par WebLogic 10.3.6, qui est JDK 6. Resteasy 2.3.5.Final, par exemple, pourrait avoir été compilé avec une version de Java plus récente que JDK 6.

Pour résoudre ce problème, vous devez vous assurer d'utiliser une version compatible de Resteasy qui a été compilée avec JDK 6. Vous pouvez essayer de rechercher une version plus ancienne de Resteasy, comme Resteasy 2.2.1.GA, qui est compatible avec JDK 6.

Assurez-vous également que votre environnement d'exécution utilise effectivement JDK 6 et qu'il n'y a pas de conflits ou de configurations incorrectes. Vérifiez les paramètres JAVA_HOME et PATH pour vous assurer qu'ils pointent vers le JDK 6.

Enfin, gardez à l'esprit que JDK 6 est une version obsolète et n'est plus prise en charge par Oracle. Il est recommandé de mettre à jour votre JDK vers une version plus récente pour bénéficier des dernières fonctionnalités et corrections de bogues de Java.

**Comment by aghabri** [comment]
<Jun 15, 2023 3:23:51 PM CEST> <Warning> <HTTP> <BEA-101162> <User defined listener org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap failed: java.lang.NoClassDefFoundError: org.scannotation.AnnotationDB$CrossReferenceException.
java.lang.NoClassDefFoundError: org.scannotation.AnnotationDB$CrossReferenceException
	at java.lang.J9VMInternals.verifyImpl(Native Method)

**Comment by aghabri** [comment]
<Jun 15, 2023 3:36:22 PM CEST> <Warning> <HTTP> <BEA-101162> <User defined listener org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap failed: java.lang.NoClassDefFoundError: org.scannotation.AnnotationDB$CrossReferenceException.
java.lang.NoClassDefFoundError: org.scannotation.AnnotationDB$CrossReferenceException
	at java.lang.J9VMInternals.verifyImpl(Native Method)
	at java.lang.J9VMInternals.verify(J9VMInternals.java:73)
	at java.lang.J9VMInternals.verify(J9VMInternals.java:71)
	at java.lang.J9VMInternals.initialize(J9VMInternals.java:133)
	at org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap.contextInitialized(ResteasyBootstrap.java:26)
	Truncated. see log file for complete stacktrace
Caused By: java.lang.ClassNotFoundException: org.scannotation.AnnotationDB$CrossReferenceException
	at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:297)
	at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:270)
	at weblogic.utils.classloaders.ChangeAwareClassLoader.findClass(ChangeAwareClassLoader.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:676)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:642)
	Truncated. see log file for complete stacktrace
> 
<Jun 15, 2023 3:36:22 PM CEST> <Warning> <HTTP> <BEA-101162> <User defined listener org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap failed: java.lang.NullPointerException.
java.lang.NullPointerException
	at org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrap.contextDestroyed(ResteasyBootstrap.java:37)
	at weblogic.servlet.internal.EventsManager$FireContextListenerAction.run(EventsManager.java:482)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
	at weblogic.servlet.internal.EventsManager.notifyContextDestroyedEvent(EventsManager.java:200)
	Truncated. see log file for complete stacktrace
> 
<Jun 15, 2023 3:36:23 PM CEST> <Error> <Deployer> <BEA-149265> <Failure occurred in the execution of deployment request with ID '1686836172263' for task '44'. Error is: 'weblogic.application.ModuleException: '
weblogic.application.ModuleException: 
	at weblogic.servlet.internal.WebAppModule.startContexts(WebAppModule.java:1531)
	at weblogic.servlet.internal.WebAppModule.start(WebAppModule.java:488)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:425)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:52)
	at weblogic.application.internal.flow.ModuleStateDriver.start(ModuleStateDriver.java:119)
	Truncated. see log file for complete stacktrace
Caused By: java.lang.ClassNotFoundException: org.scannotation.AnnotationDB$CrossReferenceException
	at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:297)
	at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:270)
	at weblogic.utils.classloaders.ChangeAwareClassLoader.findClass(ChangeAwareClassLoader.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:676)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:642)
	Truncated. see log file for complete stacktrace
>

**Comment by aghabri** [comment]
Could not find MessageBodyWriter for response object of type: com.socgen.gds.synoe.DonneeContratAssuranceVie of media type: application/json

**Comment by aghabri** [comment]
[new 17.txt](https://github.com/aghabri/test/files/11767928/new.17.txt)

**Comment by aghabri** [comment]
[new 17.txt](https://github.com/aghabri/test/files/11768025/new.17.txt)
